import { Recipe } from "./types";

export const INITIAL_RECIPES: Recipe[] = [
  {
    id: "rec-crispy-tortilla-wrap",
    title: "Fit Tortilla Wrap z chrupiącym kurczakiem i sosem czosnkowym",
    category: "Obiady",
    timeMinutes: 15,
    servings: 1,
    image: "wrap",
    imageUrl: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80",
    description: "Soczysty wrap z chrupiącym filetem z kurczaka w płatkach kukurydzianych, świeżymi warzywami i lekkim sosem czosnkowym na bazie Skyru.",
    kcal: 495,
    protein: 46.0,
    fat: 9.5,
    carbs: 56.0,
    tags: ["Obiad", "Wysokobiałkowe", "Szybkie (<15 min)", "Meal Prep"],
    ingredients: [
      { name: "Tortilla pełnoziarnista (1 placek)", grams: 62, kcal: 185, protein: 5.5, fat: 3.8, carbs: 32.0 },
      { name: "Pierś z kurczaka (świeża)", grams: 180, kcal: 198, protein: 40.5, fat: 2.3, carbs: 0.0 },
      { name: "Płatki kukurydziane (rozkruszone do panierki)", grams: 20, kcal: 76, protein: 1.4, fat: 0.2, carbs: 16.8 },
      { name: "Skyr naturalny (na sos czosnkowy)", grams: 60, kcal: 39, protein: 7.2, fat: 0.1, carbs: 2.4 },
      { name: "Pomidor, ogórek, sałata lodowa", grams: 100, kcal: 20, protein: 1.0, fat: 0.2, carbs: 3.5 },
      { name: "Czosnek, sól, pieprz, papryka wędzona", grams: 5, kcal: 5, protein: 0.2, fat: 0.0, carbs: 1.0 },
    ],
    instructions: [
      "Pierś z kurczaka pokrój w podłużne paski. Dopraw solą, pieprzem, czosnkiem granulowanym i wędzoną papryką.",
      "Obtocz mięso w rozkruszonych płatkach kukurydzianych i upiecz w piekarniku (190°C przez 12-14 min) lub na patelni teflonowej bez tłuszczu / we frytkownicy beztłuszczowej (Air Fryer 180°C przez 10 min).",
      "W miseczce wymieszaj Skyr z przeciśniętym ząbkiem czosnku, szczyptą soli i oregano.",
      "Placek tortilli podgrzej na suchej patelni przez 20 sekund z każdej strony, aby stał się elastyczny.",
      "Posmaruj tortillę sosem czosnkowym, ułóż liście chrupiącej sałaty, plastry pomidora, ogórka oraz upieczone paski kurczaka.",
      "Zwiń boki do środka i ciasno zroluj. Opcjonalnie podpiecz na grillu elektrycznym na złoty kolor."
    ]
  },
  {
    id: "rec-fit-quesadilla",
    title: "Wysokobiałkowa Quesadilla z wołowiną i mozzarellą light",
    category: "Kolacje",
    timeMinutes: 12,
    servings: 1,
    image: "wrap",
    imageUrl: "https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?auto=format&fit=crop&w=800&q=80",
    description: "Chrupiąca, ciągnąca się quesadilla z chudą wołowiną, czerwoną fasolą, kukurydzą i roztopioną mozzarellą light.",
    kcal: 540,
    protein: 48.5,
    fat: 14.0,
    carbs: 52.0,
    tags: ["Kolacje", "Wysokobiałkowe", "Szybkie (<15 min)"],
    ingredients: [
      { name: "Tortilla pszenna / pełnoziarnista", grams: 62, kcal: 185, protein: 5.5, fat: 3.8, carbs: 32.0 },
      { name: "Mięso mielone wołowe chude (95/5)", grams: 150, kcal: 205, protein: 31.5, fat: 7.5, carbs: 0.0 },
      { name: "Mozzarella wiórki light", grams: 50, kcal: 110, protein: 12.5, fat: 5.5, carbs: 1.0 },
      { name: "Czerwona fasola i kukurydza (odsączone)", grams: 50, kcal: 45, protein: 2.5, fat: 0.3, carbs: 8.0 },
      { name: "Sos pomidorowy / passata z ziołami", grams: 40, kcal: 15, protein: 0.8, fat: 0.1, carbs: 2.8 },
    ],
    instructions: [
      "Na patelni podsmaż mięso mielone wołowe z solą, pieprzem, kuminem i słodką papryką, aż zmieni kolor.",
      "Dodaj passatę pomidorową, fasolę oraz kukurydzę. Duś przez 3 minuty aż sos lekko odparuje i zgęstnieje.",
      "Na połowie placka tortilli rozsyp połowę mozzarelli light, wyłóż ciepły farsz mięsny i posyp resztą sera.",
      "Złóż tortillę na pół w półksiężyc.",
      "Smaż na suchej, średnio rozgrzanej patelni pod przykryciem przez 2-3 minuty z każdej strony, aż ser całkowicie się rozpuści, a placek będzie chrupiący.",
      "Pokrój na 3 trójkąty i podawaj od razu."
    ]
  },
  {
    id: "rec-fit-burger",
    title: "Soczysty Fit Burger wołowy w bułce grahamce",
    category: "Obiady",
    timeMinutes: 15,
    servings: 1,
    image: "chicken",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80",
    description: "Prawdziwy domowy burger o znakomitym makro. 100% chudej wołowiny, warzywa i sos burgerowy na bazie jogurtu greckiego.",
    kcal: 520,
    protein: 47.0,
    fat: 12.5,
    carbs: 53.0,
    tags: ["Obiad", "Wysokobiałkowe"],
    ingredients: [
      { name: "Chuda wołowina mielona (np. z udźca)", grams: 180, kcal: 246, protein: 37.8, fat: 9.0, carbs: 0.0 },
      { name: "Bułka grahamka / pełnoziarnista", grams: 70, kcal: 178, protein: 6.5, fat: 1.5, carbs: 35.0 },
      { name: "Ser cheddar / gouda light (1 plaster)", grams: 20, kcal: 56, protein: 5.6, fat: 3.2, carbs: 0.1 },
      { name: "Ogórek kiszony, pomidor, czerwona cebula", grams: 80, kcal: 18, protein: 0.8, fat: 0.1, carbs: 3.5 },
      { name: "Sos: Jogurt grecki (20g) + keczup bez cukru (15g) + musztarda", grams: 40, kcal: 26, protein: 1.8, fat: 0.8, carbs: 2.8 },
    ],
    instructions: [
      "Mięso wołowe dopraw wyłącznie świeżo mielonym pieprzem i odrobiną soli. Uformuj zwarty, płaski kotlet (nieco szerszy niż bułka).",
      "Rozgrzej mocno patelnię grillową i smaż burgera po 3-4 minuty z każdej strony. W ostatniej minucie połóż plaster sera na mięso i przykryj pokrywką, aby się roztopił.",
      "Bułkę grahamkę przekrój na pół i podpiecz na suchej patelni, aby była chrupiąca od środka.",
      "Wymieszaj jogurt grecki z keczupem i musztardą.",
      "Spód bułki posmaruj sosem, ułóż liść sałaty, gorącego burgera z serem, plastry ogórka kiszonego, pomidora i cebuli.",
      "Przykryj górną częścią bułki i dociśnij."
    ]
  },
  {
    id: "rec-shakshuka-fit",
    title: "Aromatyczna Fit Szakszuka z pomidorami, papryką i fetą",
    category: "Śniadania",
    timeMinutes: 12,
    servings: 1,
    image: "egg",
    imageUrl: "https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=800&q=80",
    description: "Jajka w koszulkach gotowane w gęstym, pikantnym sosie pomidorowo-paprykowym z dodatkiem kremowej fety i świeżych ziół.",
    kcal: 410,
    protein: 28.0,
    fat: 16.5,
    carbs: 36.0,
    tags: ["Śniadanie", "Wegetariańskie", "Szybkie (<15 min)"],
    ingredients: [
      { name: "Jajka kurze świeże (2 sztuki)", grams: 110, kcal: 157, protein: 13.8, fat: 10.5, carbs: 0.8 },
      { name: "Pomidory krojone w puszce / passata", grams: 200, kcal: 48, protein: 2.4, fat: 0.4, carbs: 8.8 },
      { name: "Papryka czerwona i cebula", grams: 100, kcal: 35, protein: 1.2, fat: 0.3, carbs: 7.0 },
      { name: "Ser Feta / Favita 12% light", grams: 35, kcal: 58, protein: 4.8, fat: 3.5, carbs: 1.2 },
      { name: "Chleb żytni na zakwasie (1 kromka)", grams: 45, kcal: 102, protein: 2.7, fat: 0.6, carbs: 20.2 },
      { name: "Oliwa z oliwek (pół łyżeczki)", grams: 3, kcal: 26, protein: 0.0, fat: 3.0, carbs: 0.0 },
    ],
    instructions: [
      "Na patelni rozgrzej kroplę oliwy. Zeszklij drobno posiekaną cebulę i pokrojoną w kostkę paprykę (ok. 3 minuty).",
      "Dodaj pomidory z puszki, czosnek, kumin (kmin rzymski), słodką paprykę, sól i pieprz. Gotuj na średnim ogniu przez 4 minuty, aż sos zredukuje się i zgęstnieje.",
      "Łyżką zrób 2 wgłębienia w sosie i wbij w nie delikatnie jajka.",
      "Przykryj patelnię pokrywką i zmniejsz ogień. Gotuj przez ok. 4-5 minut, aż białka całkowicie się zetną, a żółtka pozostaną płynne.",
      "Zdejmij z ognia, posyp pokruszoną fetą i świeżą pietruszką lub kolendrą.",
      "Zjedz bezpośrednio z patelni z kromką świeżego chleba żytniego."
    ]
  },
  {
    id: "rec-protein-french-toast",
    title: "Proteinowe Tosty Francuskie z cynamonem i owocami",
    category: "Śniadania",
    timeMinutes: 10,
    servings: 1,
    image: "oats",
    imageUrl: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=800&q=80",
    description: "Chrupiące z zewnątrz, miękkie i maślane w środku tosty nasączone masą jajeczno-białkową z cynamonem i borówkami.",
    kcal: 435,
    protein: 36.5,
    fat: 9.0,
    carbs: 51.0,
    tags: ["Śniadanie", "Wysokobiałkowe", "Desery Fit", "Szybkie (<15 min)"],
    ingredients: [
      { name: "Chleb tostowy pełnoziarnisty / graham (3 kromki)", grams: 75, kcal: 188, protein: 7.2, fat: 2.2, carbs: 33.0 },
      { name: "Jajko całe (1 szt.) + Białko jaja (1 szt.)", grams: 90, kcal: 95, protein: 11.2, fat: 5.2, carbs: 0.6 },
      { name: "Odżywka białkowa WPC wanilia / cynamon", grams: 20, kcal: 79, protein: 15.6, fat: 1.2, carbs: 1.4 },
      { name: "Mleko 2.0% / napój migdałowy", grams: 50, kcal: 25, protein: 1.6, fat: 1.0, carbs: 2.4 },
      { name: "Borówki świeże i cynamon", grams: 60, kcal: 34, protein: 0.5, fat: 0.2, carbs: 8.6 },
    ],
    instructions: [
      "W głębokim talerzu roztrzep widelcem jajko, dodatkowe białko, mleko, odżywkę białkową i pół łyżeczki cynamonu na gładki płyn.",
      "Kromki chleba zanurzaj w masie z obu stron, pozwalając im dokładnie nasiąknąć (ok. 15 sekund z każdej strony).",
      "Rozgrzej patelnię teflonową spryskaną odrobiną oliwy.",
      "Smaż tosty na średnim ogniu po ok. 2-3 minuty z każdej strony na piękny, złocisty kolor.",
      "Przełóż na talerz, posyp świeżymi borówkami i opcjonalnie polej syropem klonowym zero kalorii."
    ]
  },
  {
    id: "rec-chicken-spaghetti-fit",
    title: "Fit Spaghetti Bolognese z kurczakiem i sosem pomidorowym",
    category: "Obiady",
    timeMinutes: 20,
    servings: 1,
    image: "chicken",
    imageUrl: "https://images.unsplash.com/photo-1622973536968-3ead9e780960?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Klasyk kuchni włoskiej w wersji fit. Makaron pełnoziarnisty z gęstym sosem pomidorowo-ziołowym i chudym mielonym mięsem drobiowym.",
    kcal: 575,
    protein: 52.0,
    fat: 9.5,
    carbs: 68.0,
    tags: ["Obiad", "Wysokobiałkowe", "Meal Prep"],
    ingredients: [
      { name: "Makaron spaghetti pełnoziarnisty (suchy)", grams: 75, kcal: 262, protein: 9.8, fat: 1.8, carbs: 50.2 },
      { name: "Mięso z piersi kurczaka mielone", grams: 200, kcal: 220, protein: 44.0, fat: 2.6, carbs: 0.0 },
      { name: "Passata pomidorowa 100% z bazylią", grams: 200, kcal: 48, protein: 2.4, fat: 0.4, carbs: 8.8 },
      { name: "Czosnek, cebula, oregano, bazylia", grams: 50, kcal: 20, protein: 0.8, fat: 0.1, carbs: 4.0 },
      { name: "Parmezan tarty (na wierzch)", grams: 10, kcal: 39, protein: 3.8, fat: 2.8, carbs: 0.3 },
    ],
    instructions: [
      "Wstaw garnek z osoloną wodą i ugotuj makaron spaghetti al dente (ok. 8-9 minut).",
      "Na patelni podsmaż posiekaną cebulę i czosnek, po czym dodaj mielone mięso z kurczaka.",
      "Smaż rozdrabniając łopatką przez 5 minut, aż mięso straci surowy kolor.",
      "Wlej passatę pomidorową, dodaj suszone oregano, bazylię, sól, pieprz i szczyptę erytrytolu dla zbalansowania kwasowości pomidorów.",
      "Gotuj na wolnym ogniu przez 8-10 minut, aby smaki się połączyły.",
      "Wymieszaj sos z odcedzonym makaronem, przełóż na głęboki talerz i posyp startym parmezanem."
    ]
  },
  {
    id: "rec-protein-oats",
    title: "Proteinowa owsianka z bananem i masłem orzechowym",
    category: "Wysokobiałkowe",
    timeMinutes: 10,
    servings: 1,
    image: "oats",
    imageUrl: "https://images.unsplash.com/photo-1517673132405-a56a62b18caf?auto=format&fit=crop&w=800&q=80",
    description: "Sycące, zbilansowane śniadanie dające stabilną energię na wiele godzin. Wysoka zawartość białka i węglowodanów złożonych.",
    kcal: 510,
    protein: 38.5,
    fat: 14.2,
    carbs: 58.0,
    tags: ["Wysokobiałkowe", "Szybkie (<15 min)", "Śniadanie", "Wegetariańskie"],
    ingredients: [
      { name: "Płatki owsiane górskie", grams: 60, kcal: 225, protein: 8.1, fat: 4.2, carbs: 37.2 },
      { name: "Odżywka białkowa WPC wanilia", grams: 30, kcal: 118, protein: 23.4, fat: 1.8, carbs: 2.1 },
      { name: "Banan świeży (dojrzały)", grams: 100, kcal: 89, protein: 1.1, fat: 0.3, carbs: 22.8 },
      { name: "Masło orzechowe 100%", grams: 15, kcal: 89, protein: 4.0, fat: 7.0, carbs: 1.9 },
      { name: "Mleko 2.0% / Woda", grams: 150, kcal: 75, protein: 5.0, fat: 3.0, carbs: 7.2 },
    ],
    instructions: [
      "Płatki owsiane wsyp do rondelka, zalej mlekiem i wodą w proporcji 1:1.",
      "Gotuj na małym ogniu przez 4-5 minut, regularnie mieszając, aż owsianka nabierze gęstej, kremowej konsystencji.",
      "Zdejmij rondelek z ognia i odczekaj ok. 1-2 minuty (odżywki nie należy dodawać do wrzątku, aby się nie zwarzyła).",
      "Wsyp odżywkę białkową i energicznie wymieszaj trzepaczką lub łyżką.",
      "Przełóż do miseczki, ułóż pokrojonego w plasterki banana i dodaj czubatą łyżeczkę masła orzechowego na środek."
    ]
  },
  {
    id: "rec-curry-chicken",
    title: "Fit Kurczak Curry z ryżem jaśminowym i warzywami",
    category: "Obiady",
    timeMinutes: 20,
    servings: 1,
    image: "chicken",
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    description: "Soczysty filet z piersi kurczaka z chrupiącymi warzywami w delikatnym, aromatycznym sosie curry na mleczku kokosowym light.",
    kcal: 590,
    protein: 51.0,
    fat: 11.5,
    carbs: 68.0,
    tags: ["Obiad", "Wysokobiałkowe", "Meal Prep"],
    ingredients: [
      { name: "Pierś z kurczaka", grams: 200, kcal: 220, protein: 45.0, fat: 2.6, carbs: 0.0 },
      { name: "Ryż Jaśminowy (suchy)", grams: 75, kcal: 266, protein: 5.6, fat: 0.6, carbs: 58.5 },
      { name: "Papryka czerwona i brokuł", grams: 150, kcal: 48, protein: 2.5, fat: 0.5, carbs: 8.5 },
      { name: "Mleczko kokosowe light / Jogurt", grams: 60, kcal: 45, protein: 1.2, fat: 3.5, carbs: 2.0 },
      { name: "Oliwa z oliwek do smażenia", grams: 5, kcal: 44, protein: 0.0, fat: 5.0, carbs: 0.0 },
    ],
    instructions: [
      "Ryż jaśminowy przepłucz na sitku i ugotuj w lekko osolonej wodzie (ok. 12 minut).",
      "Pierś z kurczaka pokrój w kostkę 2x2 cm. Oprósz solą, pieprzem, kurkumą i żółtą pastą/proszkiem curry.",
      "Rozgrzej oliwę na patelni i podsmaż kurczaka na dużym ogniu przez 3-4 minuty do zrumienienia.",
      "Zmniejsz ogień, dorzuć różyczki brokuła i paski papryki. Podlej 50ml wody i duś pod przykryciem przez 5 minut.",
      "Wlej mleczko kokosowe light, wymieszaj i redukuj sos przez kolejne 2-3 minuty aż zgęstnieje.",
      "Podawaj na talerzu z ugotowanym, puszystym ryżem jaśminowym."
    ]
  },
  {
    id: "rec-banana-omelet",
    title: "Puszysty Omlet bananowo-proteinowy ze Skyrem",
    category: "Śniadania",
    timeMinutes: 12,
    servings: 1,
    image: "egg",
    imageUrl: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80",
    description: "Wysokobiałkowy omlet bez dodatku cukru ze świeżymi owocami leśnymi i chłodnym skyrem waniliowym.",
    kcal: 445,
    protein: 34.0,
    fat: 12.0,
    carbs: 48.0,
    tags: ["Śniadanie", "Szybkie (<15 min)", "Wegetariańskie"],
    ingredients: [
      { name: "Jajka kurze (2 sztuki)", grams: 110, kcal: 157, protein: 13.8, fat: 10.5, carbs: 0.8 },
      { name: "Banan dojrzały", grams: 100, kcal: 89, protein: 1.1, fat: 0.3, carbs: 22.8 },
      { name: "Skyr naturalny lub waniliowy", grams: 150, kcal: 97, protein: 18.0, fat: 0.3, carbs: 6.0 },
      { name: "Płatki owsiane zmielone na mąkę", grams: 25, kcal: 94, protein: 3.4, fat: 1.8, carbs: 15.5 },
      { name: "Borówki amerykańskie", grams: 50, kcal: 28, protein: 0.4, fat: 0.2, carbs: 7.2 },
    ],
    instructions: [
      "W misce rozgnieć widelcem dojrzałego banana na gładką papkę.",
      "Dodaj 2 całe jajka oraz zmielone płatki owsiane. Wymieszaj energicznie widelcem lub zblenduj na jednolitą masę.",
      "Rozgrzej patelnię z nieprzywierającą powłoką na małym/średnim ogniu.",
      "Wylej masę na patelnię i smaż pod przykryciem przez ok. 3-4 minuty, aż wierzch omletu się zetnie i pojawią się pęcherzyki powietrza.",
      "Ostrożnie przewróć na drugą stronę i dopiekaj jeszcze przez 1,5-2 minuty.",
      "Przełóż ciepły omlet na talerz, posmaruj zimnym skyrem i posyp świeżymi borówkami."
    ]
  },
  {
    id: "rec-salmon-bowl",
    title: "Fit Poke Bowl z pieczonym łososiem i awokado",
    category: "Obiady",
    timeMinutes: 15,
    servings: 1,
    image: "fish",
    imageUrl: "https://images.unsplash.com/photo-1546069901-d5bfd2cbfb1f?auto=format&fit=crop&w=800&q=80",
    description: "Bogaty w zdrowe kwasy tłuszczowe Omega-3 bowl z pieczonym łososiem, ryżem basmati, ogórkiem i awokado.",
    kcal: 620,
    protein: 42.0,
    fat: 24.0,
    carbs: 56.0,
    tags: ["Obiad", "Kolacje", "Zdrowe Tłuszcze"],
    ingredients: [
      { name: "Łosoś atlantycki pieczony", grams: 150, kcal: 312, protein: 30.0, fat: 21.0, carbs: 0.0 },
      { name: "Ryż Basmati ugotowany", grams: 150, kcal: 195, protein: 4.2, fat: 0.5, carbs: 43.0 },
      { name: "Awokado Hass", grams: 50, kcal: 80, protein: 1.0, fat: 7.5, carbs: 4.2 },
      { name: "Ogórek świeży i pomidorki koktajlowe", grams: 120, kcal: 22, protein: 1.0, fat: 0.2, carbs: 4.5 },
      { name: "Sos sojowy + sok ze świeżej cytryny", grams: 15, kcal: 15, protein: 1.5, fat: 0.0, carbs: 1.5 },
    ],
    instructions: [
      "Filet z łososia oprósz solą, pieprzem i sokiem z cytryny. Piecz w piekarniku nagrzanym do 180°C przez 12-14 minut (lub na patelni grillowej).",
      "Do szerokiej miski nałóż ciepły, ugotowany ryż basmati.",
      "Obok ryżu ułóż upieczonego, podzielonego na mniejsze kawałki łososia, pokrojone w kostkę awokado, plasterki ogórka oraz przekrojone pomidorki.",
      "W małej miseczce wymieszaj sos sojowy z kilkoma kroplami soku z cytryny i skrop całe danie przed podaniem."
    ]
  },
  {
    id: "rec-tuna-salad",
    title: "Ekspresowa sałatka z tuńczykiem, jajkiem i warzywami",
    category: "Szybkie (<15 min)",
    timeMinutes: 8,
    servings: 1,
    image: "salad",
    imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
    description: "Błyskawiczny, lekki posiłek bogaty w białko. Gotowy w mniej niż 10 minut!",
    kcal: 380,
    protein: 41.0,
    fat: 14.5,
    carbs: 19.0,
    tags: ["Szybkie (<15 min)", "Kolacje", "Wysokobiałkowe"],
    ingredients: [
      { name: "Tuńczyk w sosie własnym (odsączony)", grams: 130, kcal: 143, protein: 32.5, fat: 1.0, carbs: 0.0 },
      { name: "Jajko ugotowane na twardo", grams: 55, kcal: 78, protein: 6.9, fat: 5.2, carbs: 0.4 },
      { name: "Kukurydza słodka i ogórek kiszony", grams: 100, kcal: 65, protein: 2.2, fat: 0.8, carbs: 13.0 },
      { name: "Jogurt grecki naturalny (lekki sos)", grams: 30, kcal: 35, protein: 2.0, fat: 2.5, carbs: 1.2 },
      { name: "Chleb żytni na zakwasie (1 kromka)", grams: 35, kcal: 79, protein: 2.1, fat: 0.5, carbs: 15.8 },
    ],
    instructions: [
      "Tuńczyka dokładnie odsącz z zalewy na sitku i przełóż do miski.",
      "Ugotowane na twardo jajko i ogórki kiszone pokrój w drobną kostkę.",
      "Dodaj odsączoną kukurydzę oraz 1 łyżkę jogurtu greckiego.",
      "Dopraw solą i świeżo mielonym czarnym pieprzem, po czym delikatnie wymieszaj składniki.",
      "Podawaj z kromką chrupkiego lub świeżego pieczywa żytniego."
    ]
  },
  {
    id: "rec-cheesecake-fit",
    title: "Fit Serniczek jednoporcjowy ze Skyrem i owocami",
    category: "Desery Fit",
    timeMinutes: 5,
    servings: 1,
    image: "dessert",
    imageUrl: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=800&q=80",
    description: "Aksamitny, kremowy deser bez cukru z dużą porcją białka. Doskonały jako słodki fit deser bez wyrzutów sumienia.",
    kcal: 295,
    protein: 36.0,
    fat: 3.5,
    carbs: 29.0,
    tags: ["Desery Fit", "Wysokobiałkowe", "Szybkie (<15 min)"],
    ingredients: [
      { name: "Twaróg chudy / Serek Quark", grams: 150, kcal: 129, protein: 27.0, fat: 0.7, carbs: 5.2 },
      { name: "Skyr waniliowy", grams: 100, kcal: 82, protein: 10.5, fat: 0.2, carbs: 9.5 },
      { name: "Biszkopty bezcukrowe (podstawa)", grams: 15, kcal: 56, protein: 1.2, fat: 0.8, carbs: 11.0 },
      { name: "Borówki świeże / Maliny", grams: 50, kcal: 28, protein: 0.4, fat: 0.2, carbs: 7.2 },
    ],
    instructions: [
      "Na dnie pucharka lub małego słoiczka pokrusz biszkopty bezcukrowe.",
      "W miseczce zblenduj twaróg chudy ze skyrem waniliowym na aksamitny, gęsty krem (możesz dodać kilka kropel aromatu waniliowego lub odrobinę erytrytolu).",
      "Wyłóż krem twarogowy na pokruszony spód.",
      "Wierzch udekoruj świeżymi borówkami lub malinami.",
      "Możesz zjeść natychmiast lub schłodzić przez 15 minut w lodówce dla jeszcze lepszego smaku."
    ]
  }
];
